# Site settings
title: 
header-img: img/home-bg.png
email: ms.rebeccahong@gmail.com
copyright_name: rh24
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rh24
learn_profile: rh24
email_username: ms.rebeccahong@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
